needs_index:
    path:     /
    defaults: { _controller: "HandissimoBundle:Needs:index" }
    methods:  GET

needs_show:
    path:     /{id}/show
    defaults: { _controller: "HandissimoBundle:Needs:show" }
    methods:  GET

needs_new:
    path:     /new
    defaults: { _controller: "HandissimoBundle:Needs:new" }
    methods:  [GET, POST]

needs_edit:
    path:     /{id}/edit
    defaults: { _controller: "HandissimoBundle:Needs:edit" }
    methods:  [GET, POST]

needs_delete:
    path:     /{id}/delete
    defaults: { _controller: "HandissimoBundle:Needs:delete" }
    methods:  DELETE
