stafftypes_index:
    path:     /
    defaults: { _controller: "HandissimoBundle:StaffTypes:index" }
    methods:  GET

stafftypes_show:
    path:     /{id}/show
    defaults: { _controller: "HandissimoBundle:StaffTypes:show" }
    methods:  GET

stafftypes_new:
    path:     /new
    defaults: { _controller: "HandissimoBundle:StaffTypes:new" }
    methods:  [GET, POST]

stafftypes_edit:
    path:     /{id}/edit
    defaults: { _controller: "HandissimoBundle:StaffTypes:edit" }
    methods:  [GET, POST]

stafftypes_delete:
    path:     /{id}/delete
    defaults: { _controller: "HandissimoBundle:StaffTypes:delete" }
    methods:  DELETE
