staff_index:
    path:     /
    defaults: { _controller: "HandissimoBundle:Staff:index" }
    methods:  GET

staff_show:
    path:     /{id}/show
    defaults: { _controller: "HandissimoBundle:Staff:show" }
    methods:  GET

staff_new:
    path:     /new
    defaults: { _controller: "HandissimoBundle:Staff:new" }
    methods:  [GET, POST]

staff_edit:
    path:     /{id}/edit
    defaults: { _controller: "HandissimoBundle:Staff:edit" }
    methods:  [GET, POST]

staff_delete:
    path:     /{id}/delete
    defaults: { _controller: "HandissimoBundle:Staff:delete" }
    methods:  DELETE
