structurestypes_index:
    path:     /
    defaults: { _controller: "HandissimoBundle:StructuresTypes:index" }
    methods:  GET

structurestypes_show:
    path:     /{id}/show
    defaults: { _controller: "HandissimoBundle:StructuresTypes:show" }
    methods:  GET

structurestypes_new:
    path:     /new
    defaults: { _controller: "HandissimoBundle:StructuresTypes:new" }
    methods:  [GET, POST]

structurestypes_edit:
    path:     /{id}/edit
    defaults: { _controller: "HandissimoBundle:StructuresTypes:edit" }
    methods:  [GET, POST]

structurestypes_delete:
    path:     /{id}/delete
    defaults: { _controller: "HandissimoBundle:StructuresTypes:delete" }
    methods:  DELETE
